name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    
jobs:
  build:
    # Windows is currently the only platform this action supports
    runs-on: windows-latest

    steps:
      # Check-out repository
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6
        
      - name: Python GUI With TkInter
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: HPANaviConvertor.py
          mode: onefile
          enable-plugins: tk-inter

      - name: Qt GUI with PySide6
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: HPANaviGroundStation.py
          mode: onefile
          enable-plugins: pyside6
          
      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/HPANaviConvertor.exe
          include-hidden-files: true

      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/HPANaviGroundStation.exe
          include-hidden-files: true
          
